const initialState = {
  establishments: [
    {
      id: 1,
      name: "Schindler's List",
      type: 'Restaurant',
      description: 'Et aut ullam in saepe et nobis eaque. Beatae rerum explicabo necessitatibus nam.',
      address: '68, chemin de Dubois\n30581 Hubert-sur-Bonnet',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '2.3',
      slug: 'schindler-s-list',
      picture: 'https://picsum.photos/id/30/450/300',
      district: null,
    },
    {
      id: 2,
      name: 'The Pacifier',
      type: 'Restaurant',
      description: 'Minima eligendi sunt labore est unde velit. Incidunt quasi fugit dicta harum et.',
      address: '4, rue de Goncalves\n38 789 Delaunay',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '2.4',
      slug: 'the-pacifier',
      picture: 'https://picsum.photos/id/67/450/300',
      district: null,
    },
    {
      id: 3,
      name: 'Bee Movie',
      type: 'Izakaya',
      description: 'Eum omnis iusto culpa labore. A accusamus animi error cupiditate cum impedit velit nostrum.',
      address: '82, rue Maillard\n98 269 Leclercq',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '4.1',
      slug: 'bee-movie',
      picture: 'https://picsum.photos/id/92/450/300',
      district: null,
    },
    {
      id: 4,
      name: 'The Hunchback of Notre Dame',
      type: 'Restaurant',
      description: 'Suscipit ipsum odit sunt deserunt. Suscipit quos dolorem ullam aut officiis.',
      address: '3, rue de Riviere\n88 466 Petitjean',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '1.4',
      slug: 'the-hunchback-of-notre-dame',
      picture: 'https://picsum.photos/id/11/450/300',
      district: null,
    },
    {
      id: 5,
      name: "Mr. Bean's Holiday",
      type: 'Izakaya',
      description: 'Placeat atque fuga deleniti aut quia. Qui impedit deserunt natus. Culpa voluptates sint sit fugiat.',
      address: '3, place Gallet\n18816 Monnierboeuf',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '2.4',
      slug: 'mr-bean-s-holiday',
      picture: 'https://picsum.photos/id/39/450/300',
      district: null,
    },
    {
      id: 6,
      name: 'The Lovely Bones',
      type: 'Izakaya',
      description: 'Itaque animi quia quos iusto repudiandae dignissimos. Et ut aut itaque tenetur.',
      address: 'impasse de Georges\n21737 Grondin',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '2.3',
      slug: 'the-lovely-bones',
      picture: 'https://picsum.photos/id/46/450/300',
      district: null,
    },
    {
      id: 7,
      name: 'Almost Famous',
      type: 'Izakaya',
      description: 'Est est excepturi asperiores ratione vitae aperiam adipisci. Modi est mollitia et consectetur iste.',
      address: '65, place Gosselin\n99170 Philippenec',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '4.9',
      slug: 'almost-famous',
      picture: 'https://picsum.photos/id/67/450/300',
      district: null,
    },
    {
      id: 8,
      name: 'Pulp Fiction',
      type: 'Izakaya',
      description: 'Neque harum eius amet in voluptas id. Impedit et in sequi enim amet hic officiis.',
      address: '47, impasse Jacques\n22703 Leger-sur-Mer',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '3.2',
      slug: 'pulp-fiction',
      picture: 'https://picsum.photos/id/17/450/300',
      district: null,
    },
    {
      id: 9,
      name: 'Monster-in-Law',
      type: 'Izakaya',
      description: 'Beatae odio illum est nobis ut. Vero commodi et incidunt nesciunt asperiores.',
      address: '72, place Paul Humbert\n21101 Masson-sur-Leroux',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '1.9',
      slug: 'monster-in-law',
      picture: 'https://picsum.photos/id/76/450/300',
      district: null,
    },
    {
      id: 10,
      name: 'Drop Dead Fred',
      type: 'Restaurant',
      description: 'Nostrum corporis autem sint id. Molestiae quibusdam praesentium id. Fugit facere et nesciunt at.',
      address: '97, avenue Paulette Nguyen\n31077 Bonnin',
      price: null,
      openingDays: null,
      noonOpeningTime: null,
      eveningOpeningTime: null,
      website: null,
      phone: null,
      rating: '2.2',
      slug: 'drop-dead-fred',
      picture: 'https://picsum.photos/id/16/450/300',
      district: null,
    },
  ],
};

const establishmentsReducer = (state = initialState, action = {}) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default establishmentsReducer;
